<a href="https://colab.research.google.com/github/KHamdyFAN/KHamdyFAN/blob/main/NBA_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('nba.csv')

In [6]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [8]:
print(df.isna().sum())

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [9]:
updated_df = df.dropna()

In [13]:
updated_df.to_csv('/content/cleaned_data.txt', sep=',')

In [14]:
with open('cleaned_data.txt') as f:
    while True:
        data = f.read(1024)  # Reading 1024 bytes at a time
        if not data:
            break
        print(data)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wa
yne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,U
NLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
37,Jerian Grant,New York Knicks,13.0,PG,23.0,6-4,195.0,Notre Dame,1572360.0
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000.0
39,Kyle O'Quinn,New York Knicks,9.0,PF,26.0,6-10,250.0,Norfolk State,3750000.0
42,Lance Thomas,New York Knicks,42.0,SF,28.0,6-8,235.0,Duke,1636842.0
44,Derrick Williams,New York Knicks,23.0,PF,25.0,6-8,240.0,Arizona,4000000.0
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0
48,Robert Covington,Philadelphia 76ers,33.0,SF,25.0,6-9,215.0,Tennessee State,1000000.0
49,Joel Embiid,Philadelphia 76ers,21.0,C,22.0,7-0,250.0,Kansas,4626960.0
50,Jerami Grant,Philadelphia 76ers,39.0,SF,22.0,6-8,210.0,Syracuse,845059.0
51,R
ichaun Holmes,Philadelphia 76ers,22.0,PF,22.0,6-10,245.0,Bowling Green,1074169.0
52,Carl Landry,Philadelphia 76ers,7.0,PF,32.0,6-9,248.0,Purdue,6500000.0
53,Kendall Marshall,Philadelphia 76ers,5.0,PG,24.0,6-4,200.0,North Carolina,2144772.0
54,T.J. McConnell,Philadelphia 76ers,12.0,PG,24.0,6-2,200.0,Arizona,525093.0
55,Nerlens Noel,Philadelphia 76ers,4.0,PF,22.0,6-11,228.0,Kentucky,3457800.0
56,Jahlil Okafor,Philadelphia 76ers,8.0,C,20.0,6-11,275.0,Duke,4582680.0
57,Ish Smith,Philadelphia 76ers,1.0,PG,27.0,6-0,175.0,Wake Forest,947276.0
58,Nik Stauskas,Philadelphia 76ers,11.0,SG,22.0,6-6,205.0,Michigan,2869440.0
59,Hollis Thompson,Philadelphia 76ers,31.0,SG,25.0,6-8,206.0,Georgetown,947276.0
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,6-11,220.0,UNLV,525093.0
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,6-8,212.0,Missouri,13600000.0
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,6-7,220.0,USC,10050000.0
65,James Johnson,Toronto Raptors,3.0,PF,29.0,6-9,250.0,Wake Forest,2500000.0
66,Cory Joseph,Toronto R
aptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000.0
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,6-9,235.0,Kentucky,6268675.0
70,Norman Powell,Toronto Raptors,24.0,SG,23.0,6-4,215.0,UCLA,650000.0
71,Terrence Ross,Toronto Raptors,31.0,SF,25.0,6-7,195.0,Washington,3553917.0
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177.0
75,Delon Wright,Toronto Raptors,55.0,PG,24.0,6-5,190.0,Utah,1509360.0
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,6-8,225.0,North Carolina,3873398.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
79,Ian Clark,Golden State Warriors,21.0,SG,25.0,6-3,175.0,Belmont,947276.0
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,6-3,190.0,Davidson,11370786.0
81,Festus Ezeli,Golden State Warriors,31.0,C,26.0,6-11,265.0,Vanderbilt,2008748.0
82,Draymond Green,Golden State Warriors,23.0,PF,26.0,6-7,230.0,Michigan State,14260870.0
83,Andre Iguodala,Golden State Warriors,9.0,S
F,32.0,6-6,215.0,Arizona,11710456.0
85,Kevon Looney,Golden State Warriors,36.0,SF,20.0,6-9,220.0,UCLA,1131960.0
86,James Michael McAdoo,Golden State Warriors,20.0,SF,23.0,6-9,240.0,North Carolina,845059.0
87,Brandon Rush,Golden State Warriors,4.0,SF,30.0,6-6,220.0,Kansas,1270964.0
88,Marreese Speights,Golden State Warriors,5.0,C,28.0,6-10,255.0,Florida,3815000.0
89,Klay Thompson,Golden State Warriors,11.0,SG,26.0,6-7,215.0,Washington State,15501000.0
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444.0
93,Jamal Crawford,Los Angeles Clippers,11.0,SG,36.0,6-5,195.0,Michigan,5675000.0
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,6-6,225.0,Michigan State,525093.0
95,Jeff Green,Los Angeles Clippers,8.0,SF,29.0,6-9,235.0,Georgetown,9650000.0
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726.0
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,6-7,215.0,Syracuse,1100602.0
98,
DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
99,Luc Richard Mbah a Moute,Los Angeles Clippers,12.0,PF,29.0,6-8,230.0,UCLA,947276.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3376000.0
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000.0
104,Austin Rivers,Los Angeles Clippers,25.0,PG,23.0,6-4,200.0,Duke,3110796.0
105,C.J. Wilcox,Los Angeles Clippers,30.0,SG,25.0,6-5,195.0,Washington,1159680.0
106,Brandon Bass,Los Angeles Lakers,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
107,Tarik Black,Los Angeles Lakers,28.0,C,24.0,6-9,250.0,Kansas,845059.0
108,Anthony Brown,Los Angeles Lakers,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
110,Jordan Clarkson,Los Angeles Lakers,6.0,PG,24.0,6-5,194.0,Missouri,845059.0
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217.0
113,Ryan Kelly,Los Angeles Lakers,4.0,PF,25.0,6-11,230.0,Duke,1724250.0
114,Larry Nance Jr.
,Los Angeles Lakers,7.0,PF,23.0,6-9,230.0,Wyoming,1155600.0
115,Julius Randle,Los Angeles Lakers,30.0,PF,21.0,6-9,250.0,Kentucky,3132240.0
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120.0
117,Robert Sacre,Los Angeles Lakers,50.0,C,27.0,7-0,270.0,Gonzaga,981348.0
119,Metta World Peace,Los Angeles Lakers,37.0,SF,36.0,6-7,260.0,St. John's,947276.0
120,Nick Young,Los Angeles Lakers,0.0,SF,31.0,6-7,210.0,USC,5219169.0
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192.0
125,Archie Goodwin,Phoenix Suns,20.0,SG,21.0,6-5,200.0,Kentucky,1160160.0
126,John Jenkins,Phoenix Suns,23.0,SG,25.0,6-4,215.0,Vanderbilt,981348.0
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
129,Jon Leuer,Phoenix Suns,30.0,PF,27.0,6-10,228.0,Wisconsin,1035000.0

130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0
131,Ronnie Price,Phoenix Suns,14.0,PG,32.0,6-2,190.0,Utah Valley,947276.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
134,T.J. Warren,Phoenix Suns,12.0,SF,22.0,6-8,230.0,North Carolina State,2041080.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
136,Quincy Acy,Sacramento Kings,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
137,James Anderson,Sacramento Kings,5.0,SG,27.0,6-6,213.0,Oklahoma State,1015421.0
139,Caron Butler,Sacramento Kings,31.0,SF,36.0,6-7,228.0,Connecticut,1449187.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
142,Darren Collison,Sacramento Kings,7.0,PG,28.0,6-0,175.0,UCLA,5013559.0
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950.0
144,Seth Curry,Sacramento Kings,30.0,SG,25.0,6-2,185.0,Duke,947276.0
145,Duje Dukan,Sacramento Kings,26.0,PF,24.0,6-9,220.0,Wisconsin,525093.0
146,Rudy Gay,Sacramento Kings,8.0,SF,
29.0,6-8,230.0,Connecticut,12403101.0
147,Kosta Koufos,Sacramento Kings,41.0,C,27.0,7-0,265.0,Ohio State,7700000.0
148,Ben McLemore,Sacramento Kings,23.0,SG,23.0,6-5,195.0,Kansas,3156600.0
149,Eric Moreland,Sacramento Kings,25.0,PF,24.0,6-10,238.0,Oregon State,845059.0
150,Rajon Rondo,Sacramento Kings,9.0,PG,30.0,6-1,186.0,Kentucky,9500000.0
151,Cameron Bairstow,Chicago Bulls,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500.0
154,Mike Dunleavy,Chicago Bulls,34.0,SG,35.0,6-9,230.0,Duke,4500000.0
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000.0
158,Justin Holiday,Chicago Bulls,7.0,SG,27.0,6-6,185.0,Washington,947276.0
159,Doug McDermott,Chicago Bulls,3.0,SF,24.0,6-8,225.0,Creighton,2380440.0
161,E'Twaun Moore,Chicago Bulls,55.0,SG,27.0,6-4,191.0,Purdue,1015421.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
163,Bobby Portis,Chicago Bu
lls,5.0,PF,21.0,6-11,230.0,Arkansas,1391160.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
165,Tony Snell,Chicago Bulls,20.0,SF,24.0,6-7,200.0,New Mexico,1535880.0
166,Matthew Dellavedova,Cleveland Cavaliers,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029.0
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501.0
170,Richard Jefferson,Cleveland Cavaliers,24.0,SF,35.0,6-7,233.0,Arizona,947276.0
172,James Jones,Cleveland Cavaliers,1.0,SG,35.0,6-8,218.0,Miami (FL),947276.0
173,Sasha Kaun,Cleveland Cavaliers,14.0,C,31.0,6-11,260.0,Kansas,1276000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0
177,Iman Shumpert,Cleveland Cavaliers,4.0,SG,25.0,6-5,220.0,Georgia Tech,8988765.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
180,Mo Williams,Cleveland Cavaliers,52.
0,PG,33.0,6-1,198.0,Alabama,2100000.0
181,Joel Anthony,Detroit Pistons,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
182,Aron Baynes,Detroit Pistons,12.0,C,29.0,6-10,260.0,Washington State,6500000.0
183,Steve Blake,Detroit Pistons,22.0,PG,36.0,6-3,172.0,Maryland,2170465.0
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444.0
185,Reggie Bullock,Detroit Pistons,25.0,SF,25.0,6-7,205.0,North Carolina,1252440.0
186,Kentavious Caldwell-Pope,Detroit Pistons,5.0,SG,23.0,6-5,205.0,Georgia,2891760.0
187,Spencer Dinwiddie,Detroit Pistons,8.0,PG,23.0,6-6,200.0,Colorado,845059.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000.0
190,Darrun Hilliard,Detroit Pistons,6.0,SF,23.0,6-6,205.0,Villanova,600000.0
191,Reggie Jackson,Detroit Pistons,1.0,PG,26.0,6-3,208.0,Boston College,13913044.0
192,Stanley Johnson,Detroit Pistons,3.0,SF,20.0,6-7,245.0,Arizona,2841960.0
193,Jodie Meeks,Detroit Pistons,20
.0,SG,28.0,6-4,210.0,Kentucky,6270000.0
194,Marcus Morris,Detroit Pistons,13.0,PF,26.0,6-9,235.0,Kansas,5000000.0
195,Anthony Tolliver,Detroit Pistons,43.0,PF,31.0,6-8,240.0,Creighton,3000000.0
196,Lavoy Allen,Indiana Pacers,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
197,Rakeem Christmas,Indiana Pacers,25.0,PF,24.0,6-9,250.0,Syracuse,1007026.0
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106.0
200,George Hill,Indiana Pacers,3.0,PG,30.0,6-3,188.0,IUPUI,8000000.0
201,Jordan Hill,Indiana Pacers,27.0,C,28.0,6-10,235.0,Arizona,4000000.0
202,Solomon Hill,Indiana Pacers,44.0,SF,25.0,6-7,225.0,Arizona,1358880.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
206,Glenn Robinson III,Indiana Pacers,40.0,SG,22.0,6-7,222.0,Michigan,1100000.0
207,Rodney Stuckey,Indiana Pacers,2.0,PG,30.0,6-5,205.0,Eastern Washington,7000000.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
209,Shayne Whittington,Indiana Pacers,42.0,PF,25.0,6-11,250.0,Western Michig
an,845059.0
210,Joe Young,Indiana Pacers,1.0,PG,23.0,6-2,180.0,Oregon,1007026.0
212,Jerryd Bayless,Milwaukee Bucks,19.0,PG,27.0,6-3,200.0,Arizona,3000000.0
213,Michael Carter-Williams,Milwaukee Bucks,5.0,PG,24.0,6-6,190.0,Syracuse,2399040.0
214,Jared Cunningham,Milwaukee Bucks,9.0,SG,25.0,6-4,195.0,Oregon State,947276.0
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
216,John Henson,Milwaukee Bucks,31.0,PF,25.0,6-11,229.0,North Carolina,2943221.0
218,O.J. Mayo,Milwaukee Bucks,3.0,SG,28.0,6-5,210.0,USC,8000000.0
219,Khris Middleton,Milwaukee Bucks,22.0,SG,24.0,6-8,234.0,Texas A&M,14700000.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0
221,Steve Novak,Milwaukee Bucks,6.0,SF,32.0,6-10,225.0,Marquette,295327.0
222,Johnny O'Bryant III,Milwaukee Bucks,77.0,PF,23.0,6-9,257.0,LSU,845059.0
223,Jabari Parker,Milwaukee Bucks,12.0,PF,21.0,6-8,250.0,Duke,5152440.0
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
225,Greivis Vasquez,Milwaukee
Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000.0
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
227,Justin Anderson,Dallas Mavericks,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
228,J.J. Barea,Dallas Mavericks,5.0,PG,31.0,6-0,185.0,Northeastern,4290000.0
229,Jeremy Evans,Dallas Mavericks,21.0,SF,28.0,6-9,200.0,Western Kentucky,1100602.0
230,Raymond Felton,Dallas Mavericks,2.0,PG,31.0,6-1,205.0,North Carolina,3950313.0
231,Devin Harris,Dallas Mavericks,34.0,PG,33.0,6-3,185.0,Wisconsin,4053446.0
232,David Lee,Dallas Mavericks,42.0,PF,33.0,6-9,245.0,Florida,2085671.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
234,JaVale McGee,Dallas Mavericks,11.0,C,28.0,7-0,270.0,Nevada,1270964.0
238,Chandler Parsons,Dallas Mavericks,25.0,SF,27.0,6-10,230.0,Florida,15361500.0
239,Dwight Powell,Dallas Mavericks,7.0,PF,24.0,6-11,240.0,Stanford,845059.0
240,Charlie Villanueva,Dallas Mavericks,3.0,PF,31.0,6-11,232.0,Connecticut,947276.0
241,Deron Williams,Dallas Mavericks,8.
0,PG,31.0,6-3,200.0,Illinois,5378974.0
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
243,Michael Beasley,Houston Rockets,8.0,SF,27.0,6-10,235.0,Kansas State,306527.0
244,Patrick Beverley,Houston Rockets,2.0,PG,27.0,6-1,185.0,Arkansas,6486486.0
245,Corey Brewer,Houston Rockets,33.0,SG,30.0,6-9,186.0,Florida,8229375.0
247,Sam Dekker,Houston Rockets,7.0,SF,22.0,6-9,230.0,Wisconsin,1646400.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438.0
250,Montrezl Harrell,Houston Rockets,35.0,PF,22.0,6-8,240.0,Louisville,1000000.0
252,Terrence Jones,Houston Rockets,6.0,PF,24.0,6-9,252.0,Kentucky,2489530.0
253,K.J. McDaniels,Houston Rockets,32.0,SG,23.0,6-6,205.0,Clemson,3189794.0
256,Jason Terry,Houston Rockets,31.0,SG,38.0,6-2,185.0,Arizona,947276.0
257,Jordan Adams,Memphis Grizzlies,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
258,Tony Allen,Memphis Grizzlies,9.0,SG,34.0,6-4,213.0,Oklahoma State,51
58539.0
259,Chris Andersen,Memphis Grizzlies,7.0,PF,37.0,6-10,245.0,Blinn College,5000000.0
260,Matt Barnes,Memphis Grizzlies,22.0,SF,36.0,6-7,226.0,UCLA,3542500.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426.0
263,Bryce Cotton,Memphis Grizzlies,8.0,PG,23.0,6-1,165.0,Providence,700902.0
266,JaMychal Green,Memphis Grizzlies,0.0,PF,25.0,6-9,227.0,Alabama,845059.0
267,P.J. Hairston,Memphis Grizzlies,19.0,SF,23.0,6-6,230.0,North Carolina,1201440.0
268,Jarell Martin,Memphis Grizzlies,10.0,PF,22.0,6-10,239.0,LSU,1230840.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
272,Lance Stephenson,Memphis Grizzlies,1.0,SF,25.0,6-5,230.0,Cincinnati,9000000.0
274,Brandan Wright,Memphis Grizzlies,34.0,PF,28.0,6-10,210.0,North Carolina,5464000.0
276,Ryan Anderson,New Orleans Pelicans,33.0,PF,28.0,6-10,240.0,California,8500000.0
278,Luke Babbitt,New Orleans Pelicans,8.0,SF,26.0,6-
9,225.0,Nevada,1100602.0
279,Norris Cole,New Orleans Pelicans,30.0,PG,27.0,6-2,175.0,Cleveland State,3036927.0
280,Dante Cunningham,New Orleans Pelicans,44.0,PF,29.0,6-8,230.0,Villanova,2850000.0
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730.0
282,Bryce Dejean-Jones,New Orleans Pelicans,31.0,SG,23.0,6-6,203.0,Iowa State,169883.0
283,Toney Douglas,New Orleans Pelicans,16.0,PG,30.0,6-2,195.0,Florida State,1164858.0
284,James Ennis,New Orleans Pelicans,4.0,SF,25.0,6-7,210.0,Long Beach State,845059.0
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586.0
286,Tim Frazier,New Orleans Pelicans,2.0,PG,25.0,6-1,170.0,Penn State,845059.0
287,Alonzo Gee,New Orleans Pelicans,15.0,SF,29.0,6-6,225.0,Alabama,1320000.0
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
290,Jrue Holiday,New Orleans Pelicans,11.0,PG,25.0,6-4,205.0,UCLA,10595507.0
291,Orlando Johns
on,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0
293,Quincy Pondexter,New Orleans Pelicans,20.0,SF,28.0,6-7,220.0,Washington,3382023.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
295,Kyle Anderson,San Antonio Spurs,1.0,SF,22.0,6-9,230.0,UCLA,1142880.0
296,Matt Bonner,San Antonio Spurs,15.0,C,36.0,6-10,235.0,Florida,947276.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
300,Danny Green,San Antonio Spurs,14.0,SG,28.0,6-6,215.0,North Carolina,10000000.0
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500.0
303,Kevin Martin,San Antonio Spurs,23.0,SG,33.0,6-7,199.0,Western Carolina,200600.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
305,Patty Mills,San Antonio Spurs,8.0,PG,27.0,6-0,185.0,Saint Mary's,3578947.0
307,Jonathon Simmons,San Antonio Spurs,17.0,SG,26.0,6-6,195.0,Houston,525093.0
308,David West,San Antonio Spurs,30.0,PF,35.0,6-9,250.0,Xavier,1499187.0
309,Ke
nt Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
313,Kris Humphries,Atlanta Hawks,43.0,PF,31.0,6-9,235.0,Minnesota,1000000.0
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0

In [15]:
groupby_df = df.groupby('Team')['Salary'].mean()

In [16]:
groupby_df.head()

Team
Atlanta Hawks        4.860197e+06
Boston Celtics       4.181505e+06
Brooklyn Nets        3.501898e+06
Charlotte Hornets    5.222728e+06
Chicago Bulls        5.785559e+06
Name: Salary, dtype: float64

In [18]:
groupby_age = df.groupby('Position')['Age'].mean()

In [19]:
groupby_age.head()

Position
C     27.371795
PF    27.160000
PG    26.847826
SF    26.858824
SG    26.539216
Name: Age, dtype: float64

In [20]:
middle = len(updated_df) / 2

In [21]:
df_first_half = updated_df.iloc[:int(middle)]

In [23]:
df_first_half.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
216,John Henson,Milwaukee Bucks,31.0,PF,25.0,6-11,229.0,North Carolina,2943221.0
218,O.J. Mayo,Milwaukee Bucks,3.0,SG,28.0,6-5,210.0,USC,8000000.0
219,Khris Middleton,Milwaukee Bucks,22.0,SG,24.0,6-8,234.0,Texas A&M,14700000.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0

In [22]:
df_second_half = updated_df.iloc[int(middle):]

In [25]:
df_second_half.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
221,Steve Novak,Milwaukee Bucks,6.0,SF,32.0,6-10,225.0,Marquette,295327.0
222,Johnny O'Bryant III,Milwaukee Bucks,77.0,PF,23.0,6-9,257.0,LSU,845059.0
223,Jabari Parker,Milwaukee Bucks,12.0,PF,21.0,6-8,250.0,Duke,5152440.0
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000.0

In [26]:
concatenated_df = pd.concat([df_first_half, df_second_half])

In [29]:
concatenated_df.sort_values(by='Salary', ascending=False).head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0

In [30]:
print(concatenated_df.isna().sum())

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [32]:
age_bins = pd.cut(df['Age'], bins=[20, 25, 30, 35],
labels=['Young', 'Middle-aged', 'Senior'])
print(age_bins)

0            Young
1            Young
2      Middle-aged
3            Young
4      Middle-aged
          ...
453    Middle-aged
454          Young
455    Middle-aged
456    Middle-aged
457            NaN
Name: Age, Length: 458, dtype: category
Categories (3, object): ['Young' < 'Middle-aged' < 'Senior']